server:
  servlet:
    context-path: /nea
  port: 8080

spring:
  main:
    log-startup-info: false
  jackson:
    serialization:
      indent-output: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

nea-gateway:
  url: https://api.nasa.gov
  name: neaGateway
  apiKey: ${API_KEY}
  dateRangeInvalid: 7

logging.level.com.tiagobani.neaapi.gateways.NeaGateway: DEBUG

feign:
  client:
    config:
      default:
        Connecttimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC